version: '3.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
    - cluster.name=docker-cluster
    ports:
    - 9200:9200
    - 9300:9300
    networks:
      - webnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    environment:
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_URL: http://192.168.1.186:9200
    ports:
    - "5601:5601"

    networks:
      - webnet
networks:
  webnet:
