#web:
#    image: elasticsearchproject:1.0
#    command: ./run-production.sh
#    volumes:
#        - .:/code
#    ports:
#        - "8000:80"



version: '3'

services:
  web:
    build: .
    command: ./run.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"

